name: LuckyVotes
version: '${version}'
main: nl.chimpgamer.luckyvotes.LuckyVotesPlugin
api-version: '1.19'
loader: nl.chimpgamer.luckyvotes.LuckyVotesLoader

authors:
  - ChimpGamer

dependencies:
  - name: UltimateVotes
    required: false
    bootstrap: false
  - name: VotingPlugin
    required: false
    bootstrap: false
